version: "3"
services:


  nginx:
    build: ./web/load-balancer/nginx
    ports:
      - "80:80"
    depends_on:
      - home-app
      - admin-app


  home-app:
    build: ./web/app-services/home/app
    volumes:
      - "./web/app-services/home/app:/usr/src/app"
    # env_file: .env
    command: gulp

  admin-app:
    build: ./web/app-services/admin/app
    volumes:
      - "./web/app-services/admin/app:/usr/src/app"
    # env_file: .env
    command: gulp
    # ports:
    #   - "4000:4000"


  accounts-api:
    build: ./web/api-services/accounts/api
    volumes:
      - "./web/api-services/accounts/api:/usr/src/app"
    depends_on:
      - accounts-db
      - accounts-redis
    command: npm start
    # ports:
    #   - "3000:3000"


  accounts-db:
    image: mongo:latest
    volumes:
      - "./web/api-services/accounts/mongo/data/db:/data/db"
    env_file: ./web/api-services/accounts/mongo/.env

  accounts-redis:
    image: "redis:alpine"
    volumes:
      - "./web/api-services/accounts/redis/redis.conf:/usr/local/etc/redis/redis.conf"
    command: redis-server /usr/local/etc/redis/redis.conf


  # command: bash -c "npm update && npm install"
    

  # to start: docker-compose up

  # Docker Commands:
    # command: node ./dist/index.js
    # docker stop $(docker ps -a -q)
    # docker rm $(docker ps -a -q)
    # docker rmi $(docker images -a -q)