version: "3"
services:


  nginx:
    build: ./web/nginx
    ports:
      - "80:80"
    depends_on:
      - home-app
      - accounts-api


  home-app:
    build: ./web/home/app
    volumes:
      - "./web/home/app:/usr/src/app"
    depends_on:
      - redis
    # env_file: .env
    command: gulp

  accounts-app:
    build: ./web/accounts/app
    volumes:
      - "./web/accounts/app:/usr/src/app"
    depends_on:
      - redis
    # env_file: .env
    command: gulp
    # ports:
    #   - "4000:4000"


  accounts-api:
    build: ./web/accounts/api
    volumes:
      - "./web/accounts/api:/usr/src/app"
    depends_on:
      - accounts-db
    command: npm start
    # ports:
    #   - "3000:3000"


  accounts-db:
    image: mongo:latest
    volumes:
      - "./web/accounts/db/mongo/data:/mongo/data"

  redis:
    image: "redis:alpine"

  # command: bash -c "npm update && npm install"
    

  # to start: docker-compose up

  # Docker Commands:
    # command: node ./dist/index.js
    # docker stop $(docker ps -a -q)
    # docker rm $(docker ps -a -q)
    # docker rmi $(docker images -a -q)